# There aren't any actual tests yet, so for now this is just building the
# Gatsby site to verify there aren't any build errors
name: Build and Test
on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'
      - '!main'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build
